// Source: Gallantree_Group_Pty_Ltd_Share_Register_2026-05-25.xlsx
// Dates from the Transactions sheet; prices from original issue records.

export interface ShareholderSeedRow {
  name: string;
  entityTrust?: string;
  shareClass: "Founder Shares" | "Ordinary" | "Preference";
  shares: number;
  pricePerShare: string;
  beneficiallyHeld: boolean;
  dateOfIssue: string; // YYYY-MM-DD
}

export const SHAREHOLDER_SEED: ShareholderSeedRow[] = [
  {
    name: "Brett Anthony Hales",
    entityTrust: "Brett Anthony Hales ATF Hales Discretionary Trust",
    shareClass: "Founder Shares",
    shares: 3_960_504,
    pricePerShare: "0.001",
    beneficiallyHeld: false,
    dateOfIssue: "2026-03-21",
  },
  {
    name: "Clive Paul Kay",
    entityTrust: "Clive Paul Kay and Natalia Palacios-Kay ATF Kapal Australia Trust",
    shareClass: "Founder Shares",
    shares: 3_720_504,
    pricePerShare: "0.001",
    beneficiallyHeld: false,
    dateOfIssue: "2026-03-21",
  },
  {
    name: "Jesse Quentin Lee",
    entityTrust: "Jesse Quentin Lee ATF Jesse Lee Family Trust",
    shareClass: "Preference",
    shares: 1_267_971,
    pricePerShare: "0.5",
    beneficiallyHeld: false,
    dateOfIssue: "2026-03-21",
  },
  {
    name: "Richard Jerome Green",
    entityTrust: "Rockbourne Capital Pty Ltd ATF The Green Family Trust",
    shareClass: "Preference",
    shares: 836_792,
    pricePerShare: "0.5",
    beneficiallyHeld: false,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "Paul Steven Michowicz",
    entityTrust: "Paul Steven Michowicz ATF Michowicz Investment Trust",
    shareClass: "Preference",
    shares: 785_000,
    pricePerShare: "0.5",
    beneficiallyHeld: false,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "Stephen Craig Toomey",
    shareClass: "Ordinary",
    shares: 716_257,
    pricePerShare: "0.5",
    beneficiallyHeld: true,
    dateOfIssue: "2026-03-21",
  },
  {
    name: "Sharif Sethi",
    entityTrust: "Macarthur Biosciences Pty Ltd ATF Macarthur-Sethi Family Investment Trust",
    shareClass: "Preference",
    shares: 686_357,
    pricePerShare: "0.5",
    beneficiallyHeld: false,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "Louise Joy McKinnon",
    entityTrust: "Ruby McKinnon Pty Ltd ATF The McKinnon Family Trust",
    shareClass: "Ordinary",
    shares: 459_323,
    pricePerShare: "0.5",
    beneficiallyHeld: false,
    dateOfIssue: "2026-03-22",
  },
  {
    name: "James Pound",
    entityTrust: "JLP Investment Holdings Pty Ltd ATF JL Pound Family Trust",
    shareClass: "Preference",
    shares: 362_854,
    pricePerShare: "0.5",
    beneficiallyHeld: false,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "Anne Kathryn Keating",
    shareClass: "Preference",
    shares: 360_000,
    pricePerShare: "0.5",
    beneficiallyHeld: true,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "Steven John McCormick",
    entityTrust: "Steven John McCormick ATF Maca Clan Trust",
    shareClass: "Preference",
    shares: 330_000,
    pricePerShare: "0.5",
    beneficiallyHeld: false,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "David Nichols",
    entityTrust: "DN Bluestar Risk Consulting Pty Ltd",
    shareClass: "Preference",
    shares: 299_609,
    pricePerShare: "0.5",
    beneficiallyHeld: true,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "Andre Alain Patrick Allavena",
    entityTrust: "Andre Alain Patrick Allvena ATF The Allavena Family Trust",
    shareClass: "Ordinary",
    shares: 275_000,
    pricePerShare: "0.001",
    beneficiallyHeld: false,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "Ross John McKinnon",
    entityTrust: "Ross John McKinnon ATF Harvey Ruby Superannuation Fund",
    shareClass: "Ordinary",
    shares: 250_000,
    pricePerShare: "0.5",
    beneficiallyHeld: false,
    dateOfIssue: "2026-03-22",
  },
  {
    name: "Cissy Ma",
    entityTrust: "Grow and Sell Your Biz Pty Ltd",
    shareClass: "Ordinary",
    shares: 161_816,
    pricePerShare: "0.5",
    beneficiallyHeld: true,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "Andrew Paul Donovan",
    entityTrust: "Andrew Paul Donovan ATF Donovan Securities Trust",
    shareClass: "Preference",
    shares: 155_000,
    pricePerShare: "0.5",
    beneficiallyHeld: false,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "Gavin Ian Shaw and Lin Chen",
    entityTrust: "Gavin Ian Shaw and Lin Chen ATF Chen-Shaw Family Trust",
    shareClass: "Preference",
    shares: 140_000,
    pricePerShare: "0.5",
    beneficiallyHeld: false,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "Anaise Kristiane Brough",
    entityTrust: "Anaise Kristiane Brough The Anaise Kristiane Family Trust",
    shareClass: "Preference",
    shares: 125_000,
    pricePerShare: "0.5",
    beneficiallyHeld: false,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "Chris Booth",
    entityTrust: "Pasteur Partners Pty Ltd ATF Ths Acacia Trust",
    shareClass: "Ordinary",
    shares: 61_816,
    pricePerShare: "0.5",
    beneficiallyHeld: false,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "Peter James Nimmo",
    entityTrust: "Peter James Nimmo ATF Nimmo Holdings Trust",
    shareClass: "Ordinary",
    shares: 40_460,
    pricePerShare: "0.5",
    beneficiallyHeld: false,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "Isaac John Coonan",
    entityTrust: "Isaac John Coonan ABN 98 418 705 988",
    shareClass: "Ordinary",
    shares: 40_000,
    pricePerShare: "0.5",
    beneficiallyHeld: true,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "David Lynch",
    entityTrust: "Zoram Ventures Pty Ltd ATF D J Lynch Family Trust",
    shareClass: "Ordinary",
    shares: 40_000,
    pricePerShare: "0.5",
    beneficiallyHeld: false,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "Daniel Castro",
    shareClass: "Preference",
    shares: 30_000,
    pricePerShare: "0.5",
    beneficiallyHeld: true,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "Christopher Bradley",
    entityTrust: "Rimu Resources Pty Ltd",
    shareClass: "Preference",
    shares: 30_000,
    pricePerShare: "0.5",
    beneficiallyHeld: true,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "Gregory Adjemian",
    shareClass: "Ordinary",
    shares: 25_000,
    pricePerShare: "0.5",
    beneficiallyHeld: true,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "Michael Hade",
    entityTrust: "Michael Hade Consulting Pty Ltd ABN 69 641 325 233",
    shareClass: "Ordinary",
    shares: 10_000,
    pricePerShare: "0.5",
    beneficiallyHeld: true,
    dateOfIssue: "2026-03-24",
  },
  {
    name: "Wesley Colin Hill",
    entityTrust: "Wesley Colin Hill as trustee for The Hill Sampil Discretionary Trust",
    shareClass: "Ordinary",
    shares: 10_000,
    pricePerShare: "0.5",
    beneficiallyHeld: false,
    dateOfIssue: "2026-03-24",
  },
];
